# Generated by Django 5.1.2 on 2025-01-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="text",
        ),
    ]
