# Generated by Django 5.1.2 on 2025-01-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_content_comment_text'),
        ('app', '0003_userprofile'),
    ]

    operations = [
    ]
